Implemented delete mode and tests.

diff --git a/multigpg b/multigpg
--- a/multigpg
+++ b/multigpg
@@ -48,6 +48,9 @@ parseParameters(){
     elif [[ $1 = "list" || $1 = "ls" ]]
     then
         mode="list"
+    elif [[ $1 = "delete" || $1 = "d" ]]
+    then
+        mode="delete"
     elif [[ $1 = "--help" ]]
     then
         mode="printUsage"
@@ -217,6 +220,21 @@ then
             exit 1
         fi
         shred_tmp
+    elif [[ $mode = "delete" ]]
+    then
+        getPassword
+        decrypt
+        untar
+        if [ -f $working_dir/archive/$file ] || [ -d $working_dir/archive/$file ]
+        then
+            rm -r $working_dir/archive/$file
+        else
+            echo "$string_file_missing"
+            shred_tmp
+            exit 1
+        fi
+        pack_tar
+        writeback
+        shred_tmp
     fi
-
 fi
